grade = int(input("Berapa nilai murid baba st //stundent ? ,,inputh: 't -sntundent" ))
if grade >=85:print("Grade A")
elif grade >=70:print("Grade B")
elif grade >=60:print("Grade C")
elif grade >=50:print("Grade D")
else:print(" 0 Grade Tidak LULUS , under graduante ")